/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConvidadosRouteImport } from './routes/convidados'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosEventIdRouteImport } from './routes/eventos.$eventId'
import { Route as EventosEventIdDashboardRouteImport } from './routes/eventos.$eventId.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvidadosRoute = ConvidadosRouteImport.update({
  id: '/convidados',
  path: '/convidados',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventIdRoute = EventosEventIdRouteImport.update({
  id: '/eventos/$eventId',
  path: '/eventos/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventIdDashboardRoute = EventosEventIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EventosEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/convidados': typeof ConvidadosRoute
  '/login': typeof LoginRoute
  '/eventos/$eventId': typeof EventosEventIdRouteWithChildren
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$eventId/dashboard': typeof EventosEventIdDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/convidados': typeof ConvidadosRoute
  '/login': typeof LoginRoute
  '/eventos/$eventId': typeof EventosEventIdRouteWithChildren
  '/eventos': typeof EventosIndexRoute
  '/eventos/$eventId/dashboard': typeof EventosEventIdDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/convidados': typeof ConvidadosRoute
  '/login': typeof LoginRoute
  '/eventos/$eventId': typeof EventosEventIdRouteWithChildren
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$eventId/dashboard': typeof EventosEventIdDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkin'
    | '/convidados'
    | '/login'
    | '/eventos/$eventId'
    | '/eventos/'
    | '/eventos/$eventId/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkin'
    | '/convidados'
    | '/login'
    | '/eventos/$eventId'
    | '/eventos'
    | '/eventos/$eventId/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkin'
    | '/convidados'
    | '/login'
    | '/eventos/$eventId'
    | '/eventos/'
    | '/eventos/$eventId/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckinRoute: typeof CheckinRoute
  ConvidadosRoute: typeof ConvidadosRoute
  LoginRoute: typeof LoginRoute
  EventosEventIdRoute: typeof EventosEventIdRouteWithChildren
  EventosIndexRoute: typeof EventosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convidados': {
      id: '/convidados'
      path: '/convidados'
      fullPath: '/convidados'
      preLoaderRoute: typeof ConvidadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventId': {
      id: '/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof EventosEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventId/dashboard': {
      id: '/eventos/$eventId/dashboard'
      path: '/dashboard'
      fullPath: '/eventos/$eventId/dashboard'
      preLoaderRoute: typeof EventosEventIdDashboardRouteImport
      parentRoute: typeof EventosEventIdRoute
    }
  }
}

interface EventosEventIdRouteChildren {
  EventosEventIdDashboardRoute: typeof EventosEventIdDashboardRoute
}

const EventosEventIdRouteChildren: EventosEventIdRouteChildren = {
  EventosEventIdDashboardRoute: EventosEventIdDashboardRoute,
}

const EventosEventIdRouteWithChildren = EventosEventIdRoute._addFileChildren(
  EventosEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckinRoute: CheckinRoute,
  ConvidadosRoute: ConvidadosRoute,
  LoginRoute: LoginRoute,
  EventosEventIdRoute: EventosEventIdRouteWithChildren,
  EventosIndexRoute: EventosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
